# Data Splitting
input_dir: "input"
output_dir: "split_data"
train_ratio: 0.8
train_dir: "split_data/train"
test_dir: "split_data/test"

# Transformer
height: 224
width: 224
random_rotation_degrees: 40
random_affine_degrees: 20
random_translation: [0.1, 0.1]
brightness: 0.1
contrast: 0.1
saturation: 0.1
hue: 0.1
loader_dir: "loaders"
batch_size: 32

# Training
classes: ["bike", "bottle", "chair", "cup", "fork", "knife", "plant", "shoe", "spoon", "t-shirt"]
train_loader_dir: "loaders/train_loader.pkl"
test_loader_dir: "loaders/test_loader.pkl"
epochs: 5
learning_rate: 0.001

# Hyperparameter Tuning
n_trials: 100

# Main
model_path: "model/model.pth"