# Data Splitting
input_dir: "input"
output_dir: "split_data"
train_ratio: 0.8

# Transformer
random_rotation_degrees: 30
random_affine_degrees: 20
random_translation: (0.1, 0.1)
brightness: 0.1
contrast: 0.1
saturation: 0.1
hue: 0.1
loader_dir: loaders
batch_size: 32